### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by andyzito**
- [x] Initial README draft
- [x] Mention that docker subdirs are for prod deployment
- [x] Include Jest testing setup/usasge
- [x] Include Cypress testing setup/usage
- [x] Fix anchor links (GitHub markdown is not as cool as Obsidian markdown)

### CODE REVIEW

**Comment by kwiliarty** [comment]
That looks like a great list. Thanks for tackling this @andyzito .

**Comment by andyzito** [comment]
@kwiliarty I think this is in a good place so far. I'm gonna need a hand with the Jest/Cypress stuff, my notes there are not as thorough

**Comment by kwiliarty** [comment]
That looks good. I'll try to add the jest and cypress bits soon. Thanks again!

**Comment by kwiliarty** [comment]
@andyzito I've filled in some gaps. Let me know what you think and mark it ready for review when you are happy with it.

**Comment by kwiliarty** [comment]
Actually, I think I'll just integrate this. I really appreciate the help, and I hope you're having fun with it.

**Pull request merged**
